Repository RoDaMo/pds-back-end, pull requests merged in 2023-04, with the labels that each got.

#17 fix: fixing redis error and namespace naming mistake
  API/ApiResponse.cs
  Controllers/ChampionshipController.cs
  Controllers/IndexController.cs
  Models/Championship.cs
  Models/Sport.cs
  Program.cs
  Services/ChampionshipService.cs
  Services/DbService.cs
  Services/ElasticService.cs
  Services/RedisService.cs
  Validations/ChampionshipValidator.cs
  pds-back-end.csproj
Labels: bug

#18 bugfixes
  API/ApiResponse.cs
  Controllers/ChampionshipController.cs
  Controllers/IndexController.cs
  Controllers/SportController.cs
  Models/Championship.cs
  Models/Sport.cs
  Program.cs
  Services/ChampionshipService.cs
  Services/DbService.cs
  Services/ElasticService.cs
  Services/RedisService.cs
  Services/SportService.cs
  Validations/ChampionshipValidator.cs
  pds-back-end.csproj
Labels: bug, enhancement

#20 feat: internacionalization completed
  Controllers/ChampionshipController.cs
  PlayOffsApi.csproj
  PlayOffsApi.sln
  Program.cs
  Resources/Validations/Championship/Championship.Designer.cs
  Resources/Validations/Championship/Championship.en.Designer.cs
  Resources/Validations/Championship/Championship.en.resx
  Resources/Validations/Championship/Championship.resx
  Resources/Validations/Generic/Generic.Designer.cs
  Resources/Validations/Generic/Generic.en.resx
  Resources/Validations/Generic/Generic.resx
  Services/ChampionshipService.cs
  Services/ElasticService.cs
  Validations/ChampionshipValidator.cs
  pds-back-end.csproj
Labels: enhancement

#21 feat: internacionalization completed
  Controllers/ChampionshipController.cs
  PlayOffsApi.csproj
  PlayOffsApi.sln
  Program.cs
  Resources/Validations/Championship/Championship.Designer.cs
  Resources/Validations/Championship/Championship.en.Designer.cs
  Resources/Validations/Championship/Championship.en.resx
  Resources/Validations/Championship/Championship.resx
  Resources/Validations/Generic/Generic.Designer.cs
  Resources/Validations/Generic/Generic.en.resx
  Resources/Validations/Generic/Generic.resx
  Services/ChampionshipService.cs
  Services/ElasticService.cs
  Validations/ChampionshipValidator.cs
  pds-back-end.csproj
Labels: enhancement

#29 25 teams registration
  Controllers/TeamController.cs
  Models/Team.cs
  Program.cs
  Services/TeamService.cs
  Validations/ChampionshipValidator.cs
  Validations/TeamValidator.cs
Labels: enhancement

#31 feat: endpoint for user authentication
  Controllers/AuthController.cs
  Models/User.cs
  Services/AuthService.cs
Labels: enhancement
